import type { CatalogExerciseDefinition } from '@wasabi-cross/schemas';

/**
 * Definición de un ejercicio del catálogo pre-cargado. Además de nombre y categoría, lleva
 * lo que Estadísticas necesita para comparar por capacidad y grupo muscular, y lo que se
 * usa para buscar: disciplinas y equipo. El segmento no: sale del grupo primario.
 *
 * No lleva la medición: sale de la categoría (spec §5.1). Por eso la hipertrofia se mide en
 * repeticiones sin que nadie lo escriba acá.
 */
export type CatalogExercise = CatalogExerciseDefinition;

/**
 * Catálogo pre-cargado: los 120 ejercicios de spec §5.3 —los 62 de ADR-0009 y los 58 de
 * ADR-0010, con Hybrid y Pilates—. El usuario nuevo lo ve sin tener que cargar nada.
 *
 * Cada entrada lleva una clave estable: el seed compara por ella, así que un ejercicio se
 * puede renombrar sin duplicarse. Un ejercicio que una disciplina mide distinto es otro
 * ejercicio: el Sled Push de funcional va en repeticiones y el de Hyrox, en metros.
 */
export const EXERCISE_CATALOG: readonly CatalogExercise[] = [
  // --- Musculación ---
  {
    catalogKey: 'back-squat',
    name: 'Sentadilla trasera',
    category: 'fuerza',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'gluteo', 'core'],
    disciplines: ['musculacion', 'crossfit', 'hybrid'],
    equipment: 'barra',
  },
  {
    catalogKey: 'front-squat',
    name: 'Sentadilla frontal',
    category: 'fuerza',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'core', 'gluteo'],
    disciplines: ['musculacion', 'crossfit'],
    equipment: 'barra',
  },
  {
    catalogKey: 'peso-muerto-convencional',
    name: 'Peso muerto convencional',
    category: 'fuerza',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'isquiotibiales',
    muscleGroups: ['isquiotibiales', 'espalda_baja', 'gluteo', 'antebrazo'],
    disciplines: ['musculacion', 'crossfit', 'hybrid'],
    equipment: 'barra',
  },
  {
    catalogKey: 'peso-muerto-rumano',
    name: 'Peso muerto rumano',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'isquiotibiales',
    muscleGroups: ['isquiotibiales', 'gluteo', 'espalda_baja'],
    disciplines: ['musculacion'],
    equipment: 'barra',
  },
  {
    catalogKey: 'press-banca-plano',
    name: 'Press banca plano',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'pectoral',
    muscleGroups: ['pectoral', 'triceps', 'hombro'],
    disciplines: ['musculacion', 'crossfit'],
    equipment: 'barra',
  },
  {
    catalogKey: 'press-banca-inclinado',
    name: 'Press banca inclinado',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'pectoral',
    muscleGroups: ['pectoral', 'hombro', 'triceps'],
    disciplines: ['musculacion'],
    equipment: 'barra',
  },
  {
    catalogKey: 'press-militar',
    name: 'Press militar',
    category: 'fuerza',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'hombro',
    muscleGroups: ['hombro', 'triceps', 'core'],
    disciplines: ['musculacion', 'crossfit', 'hybrid'],
    equipment: 'barra',
  },
  {
    catalogKey: 'remo-con-barra',
    name: 'Remo con barra',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'espalda',
    muscleGroups: ['espalda', 'biceps'],
    disciplines: ['musculacion'],
    equipment: 'barra',
  },
  {
    catalogKey: 'dominadas-lastradas',
    name: 'Dominadas lastradas',
    category: 'fuerza',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'espalda',
    muscleGroups: ['espalda', 'biceps'],
    disciplines: ['musculacion', 'crossfit'],
    equipment: 'barra_dominadas',
  },
  {
    catalogKey: 'curl-biceps-barra',
    name: 'Curl bíceps con barra',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'biceps',
    muscleGroups: ['biceps', 'antebrazo'],
    disciplines: ['musculacion'],
    equipment: 'barra',
  },
  {
    catalogKey: 'curl-martillo',
    name: 'Curl martillo',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'biceps',
    muscleGroups: ['biceps', 'antebrazo'],
    disciplines: ['musculacion'],
    equipment: 'mancuerna',
  },
  {
    catalogKey: 'extension-triceps-polea',
    name: 'Extensión tríceps en polea',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'triceps',
    muscleGroups: ['triceps'],
    disciplines: ['musculacion'],
    equipment: 'polea',
  },
  {
    catalogKey: 'press-frances',
    name: 'Press francés',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'triceps',
    muscleGroups: ['triceps'],
    disciplines: ['musculacion'],
    equipment: 'barra',
  },
  {
    catalogKey: 'prensa-piernas',
    name: 'Prensa de piernas',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps'],
    disciplines: ['musculacion'],
    equipment: 'maquina',
  },
  {
    catalogKey: 'curl-femoral',
    name: 'Curl femoral',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'isquiotibiales',
    muscleGroups: ['isquiotibiales'],
    disciplines: ['musculacion'],
    equipment: 'maquina',
  },
  {
    catalogKey: 'elevacion-gemelos',
    name: 'Elevación de gemelos',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'gemelo',
    muscleGroups: ['gemelo'],
    disciplines: ['musculacion'],
    equipment: 'maquina',
  },
  {
    catalogKey: 'hip-thrust',
    name: 'Hip thrust',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'gluteo',
    muscleGroups: ['gluteo', 'isquiotibiales'],
    disciplines: ['musculacion'],
    equipment: 'barra',
  },
  {
    catalogKey: 'elevaciones-laterales',
    name: 'Elevaciones laterales',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'hombro',
    muscleGroups: ['hombro'],
    disciplines: ['musculacion'],
    equipment: 'mancuerna',
  },
  {
    catalogKey: 'crunch-abdominal',
    name: 'Crunch abdominal',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'core',
    muscleGroups: ['core'],
    disciplines: ['musculacion'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'jalon-al-pecho',
    name: 'Jalón al pecho',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'espalda',
    muscleGroups: ['espalda', 'biceps'],
    disciplines: ['musculacion'],
    equipment: 'polea',
  },
  {
    catalogKey: 'fondos-paralelas',
    name: 'Fondos en paralelas',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'triceps',
    muscleGroups: ['triceps', 'pectoral', 'hombro'],
    disciplines: ['musculacion'],
    equipment: 'paralelas',
  },
  {
    catalogKey: 'press-mancuernas-plano',
    name: 'Press con mancuernas plano',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'pectoral',
    muscleGroups: ['pectoral', 'triceps', 'hombro'],
    disciplines: ['musculacion'],
    equipment: 'mancuerna',
  },
  {
    catalogKey: 'aperturas-mancuernas',
    name: 'Aperturas con mancuernas',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'pectoral',
    muscleGroups: ['pectoral', 'hombro'],
    disciplines: ['musculacion'],
    equipment: 'mancuerna',
  },
  {
    catalogKey: 'remo-mancuerna',
    name: 'Remo con mancuerna',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'espalda',
    muscleGroups: ['espalda', 'biceps'],
    disciplines: ['musculacion'],
    equipment: 'mancuerna',
  },
  {
    catalogKey: 'remo-polea-baja',
    name: 'Remo en polea baja',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'espalda',
    muscleGroups: ['espalda', 'biceps'],
    disciplines: ['musculacion'],
    equipment: 'polea',
  },
  {
    catalogKey: 'zancadas-mancuernas',
    name: 'Zancadas con mancuernas',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'gluteo', 'isquiotibiales'],
    disciplines: ['musculacion', 'hybrid'],
    equipment: 'mancuerna',
  },
  {
    catalogKey: 'sentadilla-bulgara',
    name: 'Sentadilla búlgara',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'gluteo'],
    disciplines: ['musculacion'],
    equipment: 'mancuerna',
  },
  {
    catalogKey: 'extension-cuadriceps',
    name: 'Extensión de cuádriceps',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps'],
    disciplines: ['musculacion'],
    equipment: 'maquina',
  },
  {
    catalogKey: 'face-pull',
    name: 'Face pull',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'hombro',
    muscleGroups: ['hombro', 'espalda', 'trapecio'],
    disciplines: ['musculacion'],
    equipment: 'polea',
  },
  {
    catalogKey: 'back-extension',
    name: 'Extensión lumbar (back extension)',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'espalda_baja',
    muscleGroups: ['espalda_baja', 'gluteo', 'isquiotibiales'],
    disciplines: ['musculacion'],
    equipment: 'maquina',
  },
  {
    catalogKey: 'encogimientos-trapecio',
    name: 'Encogimientos de trapecio',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'trapecio',
    muscleGroups: ['trapecio', 'antebrazo'],
    disciplines: ['musculacion'],
    equipment: 'mancuerna',
  },
  {
    catalogKey: 'abduccion-cadera-maquina',
    name: 'Abducción de cadera en máquina',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'gluteo',
    muscleGroups: ['gluteo'],
    disciplines: ['musculacion'],
    equipment: 'maquina',
  },
  {
    catalogKey: 'elevacion-piernas-colgado',
    name: 'Elevación de piernas colgado',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'core',
    muscleGroups: ['core', 'antebrazo'],
    disciplines: ['musculacion'],
    equipment: 'barra_dominadas',
  },
  {
    catalogKey: 'crunch-polea',
    name: 'Crunch en polea',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'core',
    muscleGroups: ['core'],
    disciplines: ['musculacion'],
    equipment: 'polea',
  },
  // --- CrossFit ---
  {
    catalogKey: 'snatch',
    name: 'Snatch',
    category: 'fuerza',
    capacities: ['potencia'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo', 'hombro', 'espalda', 'cuadriceps'],
    disciplines: ['crossfit'],
    equipment: 'barra',
  },
  {
    catalogKey: 'clean-and-jerk',
    name: 'Clean and Jerk',
    category: 'fuerza',
    capacities: ['potencia'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo', 'hombro', 'cuadriceps', 'espalda'],
    disciplines: ['crossfit'],
    equipment: 'barra',
  },
  {
    catalogKey: 'push-press',
    name: 'Push Press',
    category: 'fuerza',
    capacities: ['potencia'],
    primaryMuscleGroup: 'hombro',
    muscleGroups: ['hombro', 'triceps', 'core'],
    disciplines: ['crossfit', 'hybrid'],
    equipment: 'barra',
  },
  {
    catalogKey: 'overhead-squat',
    name: 'Overhead Squat',
    category: 'fuerza',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'hombro', 'core'],
    disciplines: ['crossfit'],
    equipment: 'barra',
  },
  {
    catalogKey: 'thruster',
    name: 'Thruster',
    category: 'hipertrofia',
    capacities: ['potencia'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo', 'hombro', 'gluteo'],
    disciplines: ['crossfit', 'hybrid'],
    equipment: 'barra',
  },
  {
    catalogKey: 'wall-ball',
    name: 'Wall Ball',
    category: 'gimnastico',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo', 'cuadriceps', 'hombro'],
    disciplines: ['crossfit', 'hyrox', 'funcional', 'hybrid'],
    equipment: 'balon_medicinal',
  },
  {
    catalogKey: 'kettlebell-swing',
    name: 'Kettlebell Swing',
    category: 'gimnastico',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'gluteo',
    muscleGroups: ['gluteo', 'core', 'isquiotibiales'],
    disciplines: ['crossfit', 'funcional', 'hybrid'],
    equipment: 'kettlebell',
  },
  {
    catalogKey: 'pull-up',
    name: 'Pull-up',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'espalda',
    muscleGroups: ['espalda', 'biceps'],
    disciplines: ['crossfit', 'musculacion', 'funcional', 'hybrid'],
    equipment: 'barra_dominadas',
  },
  {
    catalogKey: 'toes-to-bar',
    name: 'Toes to Bar',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'core',
    muscleGroups: ['core', 'antebrazo'],
    disciplines: ['crossfit'],
    equipment: 'barra_dominadas',
  },
  {
    catalogKey: 'muscle-up',
    name: 'Muscle Up',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo', 'espalda', 'triceps'],
    disciplines: ['crossfit'],
    equipment: 'barra_dominadas_o_anillas',
  },
  {
    catalogKey: 'handstand-push-up',
    name: 'Handstand Push-up',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'hombro',
    muscleGroups: ['hombro', 'triceps'],
    disciplines: ['crossfit'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'box-jump',
    name: 'Box Jump',
    category: 'gimnastico',
    capacities: ['velocidad'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'gluteo'],
    disciplines: ['crossfit', 'hybrid'],
    equipment: 'caja',
  },
  {
    catalogKey: 'burpee',
    name: 'Burpee',
    category: 'gimnastico',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo'],
    disciplines: ['crossfit', 'funcional', 'hybrid'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'double-under',
    name: 'Double Under',
    category: 'gimnastico',
    capacities: ['velocidad'],
    primaryMuscleGroup: 'gemelo',
    muscleGroups: ['gemelo'],
    disciplines: ['crossfit'],
    equipment: 'cuerda_de_saltar',
  },
  {
    catalogKey: 'rope-climb',
    name: 'Rope Climb',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'espalda',
    muscleGroups: ['espalda', 'biceps', 'antebrazo'],
    disciplines: ['crossfit'],
    equipment: 'cuerda',
  },
  {
    catalogKey: 'remo-ergometro',
    name: 'Remo (ergómetro)',
    category: 'cardio',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo'],
    disciplines: ['crossfit', 'hyrox', 'hybrid'],
    equipment: 'remoergometro',
  },
  {
    catalogKey: 'assault-bike',
    name: 'Assault Bike',
    category: 'cardio',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo'],
    disciplines: ['crossfit', 'hybrid'],
    equipment: 'bicicleta_assault',
  },
  {
    catalogKey: 'ski-erg',
    name: 'SkiErg',
    category: 'cardio',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo'],
    disciplines: ['crossfit', 'hyrox', 'hybrid'],
    equipment: 'skierg',
  },
  {
    catalogKey: 'power-clean',
    name: 'Power Clean',
    category: 'fuerza',
    capacities: ['potencia'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo', 'espalda', 'cuadriceps', 'trapecio'],
    disciplines: ['crossfit'],
    equipment: 'barra',
  },
  {
    catalogKey: 'squat-clean',
    name: 'Squat Clean',
    category: 'fuerza',
    capacities: ['potencia'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo', 'cuadriceps', 'espalda', 'hombro'],
    disciplines: ['crossfit'],
    equipment: 'barra',
  },
  {
    catalogKey: 'hang-clean',
    name: 'Hang Clean',
    category: 'fuerza',
    capacities: ['potencia'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo', 'espalda', 'gluteo', 'trapecio'],
    disciplines: ['crossfit'],
    equipment: 'barra',
  },
  {
    catalogKey: 'power-snatch',
    name: 'Power Snatch',
    category: 'fuerza',
    capacities: ['potencia'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo', 'hombro', 'espalda', 'trapecio'],
    disciplines: ['crossfit'],
    equipment: 'barra',
  },
  {
    catalogKey: 'push-jerk',
    name: 'Push Jerk',
    category: 'fuerza',
    capacities: ['potencia'],
    primaryMuscleGroup: 'hombro',
    muscleGroups: ['hombro', 'triceps', 'cuadriceps', 'core'],
    disciplines: ['crossfit'],
    equipment: 'barra',
  },
  {
    catalogKey: 'split-jerk',
    name: 'Split Jerk',
    category: 'fuerza',
    capacities: ['potencia'],
    primaryMuscleGroup: 'hombro',
    muscleGroups: ['hombro', 'triceps', 'cuadriceps', 'core'],
    disciplines: ['crossfit'],
    equipment: 'barra',
  },
  {
    catalogKey: 'air-squat',
    name: 'Air Squat',
    category: 'gimnastico',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'gluteo'],
    disciplines: ['crossfit', 'funcional', 'hybrid'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'push-up',
    name: 'Push-up',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'pectoral',
    muscleGroups: ['pectoral', 'triceps', 'hombro', 'core'],
    disciplines: ['crossfit', 'funcional', 'hybrid'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'sit-up',
    name: 'Sit-up',
    category: 'gimnastico',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'core',
    muscleGroups: ['core'],
    disciplines: ['crossfit', 'funcional'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'walking-lunge',
    name: 'Walking Lunge',
    category: 'gimnastico',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'gluteo'],
    disciplines: ['crossfit', 'funcional', 'hybrid'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'chest-to-bar',
    name: 'Chest to Bar',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'espalda',
    muscleGroups: ['espalda', 'biceps'],
    disciplines: ['crossfit'],
    equipment: 'barra_dominadas',
  },
  {
    catalogKey: 'ring-dips',
    name: 'Ring Dips',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'triceps',
    muscleGroups: ['triceps', 'pectoral', 'hombro'],
    disciplines: ['crossfit'],
    equipment: 'anillas',
  },
  {
    catalogKey: 'ghd-sit-up',
    name: 'GHD Sit-up',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'core',
    muscleGroups: ['core', 'cuadriceps'],
    disciplines: ['crossfit'],
    equipment: 'ghd',
  },
  {
    catalogKey: 'dumbbell-snatch',
    name: 'Dumbbell Snatch',
    category: 'fuerza',
    capacities: ['potencia'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo', 'hombro', 'gluteo'],
    disciplines: ['crossfit', 'hybrid'],
    equipment: 'mancuerna',
  },
  {
    catalogKey: 'devil-press',
    name: 'Devil Press',
    category: 'hipertrofia',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo', 'hombro', 'gluteo'],
    disciplines: ['crossfit', 'hybrid'],
    equipment: 'mancuerna',
  },
  {
    catalogKey: 'bike-erg',
    name: 'BikeErg',
    category: 'cardio',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'gluteo', 'gemelo'],
    disciplines: ['crossfit', 'hybrid'],
    equipment: 'bikeerg',
  },
  // --- Hyrox ---
  {
    catalogKey: 'sled-push-hyrox',
    name: 'Sled Push (Hyrox)',
    category: 'distancia_carga',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'gluteo', 'core'],
    disciplines: ['hyrox', 'hybrid'],
    equipment: 'sled',
  },
  {
    catalogKey: 'sled-pull-hyrox',
    name: 'Sled Pull (Hyrox)',
    category: 'distancia_carga',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'espalda',
    muscleGroups: ['espalda', 'biceps'],
    disciplines: ['hyrox', 'hybrid'],
    equipment: 'sled',
  },
  {
    catalogKey: 'farmers-carry-hyrox',
    name: 'Farmers Carry (Hyrox)',
    category: 'distancia_carga',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'antebrazo',
    muscleGroups: ['antebrazo', 'core', 'trapecio'],
    disciplines: ['hyrox', 'hybrid'],
    equipment: 'mancuerna',
  },
  {
    catalogKey: 'sandbag-lunges',
    name: 'Sandbag Lunges',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'gluteo'],
    disciplines: ['hyrox', 'hybrid'],
    equipment: 'sandbag',
  },
  {
    catalogKey: 'burpee-broad-jump',
    name: 'Burpee Broad Jump',
    category: 'gimnastico',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo'],
    disciplines: ['hyrox', 'hybrid'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'carrera-1km-estacion',
    name: 'Carrera 1km (estación Hyrox)',
    category: 'running',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps'],
    disciplines: ['hyrox', 'hybrid'],
    equipment: 'sin_equipo',
  },
  // --- Funcional ---
  {
    catalogKey: 'sled-push',
    name: 'Sled Push',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'gluteo', 'core'],
    disciplines: ['funcional'],
    equipment: 'sled',
  },
  {
    catalogKey: 'sled-pull',
    name: 'Sled Pull',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'espalda',
    muscleGroups: ['espalda', 'biceps'],
    disciplines: ['funcional'],
    equipment: 'sled',
  },
  {
    catalogKey: 'farmers-carry',
    name: 'Farmers Carry',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'antebrazo',
    muscleGroups: ['antebrazo', 'core', 'trapecio'],
    disciplines: ['funcional'],
    equipment: 'mancuerna',
  },
  {
    catalogKey: 'battle-ropes',
    name: 'Battle Ropes',
    category: 'gimnastico',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'hombro',
    muscleGroups: ['hombro', 'core'],
    disciplines: ['funcional'],
    equipment: 'cuerda_battle',
  },
  {
    catalogKey: 'trx-row',
    name: 'TRX Row',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'espalda',
    muscleGroups: ['espalda', 'biceps'],
    disciplines: ['funcional'],
    equipment: 'trx',
  },
  {
    catalogKey: 'trx-push-up',
    name: 'TRX Push-up',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'pectoral',
    muscleGroups: ['pectoral', 'triceps'],
    disciplines: ['funcional'],
    equipment: 'trx',
  },
  {
    catalogKey: 'mountain-climbers',
    name: 'Mountain Climbers',
    category: 'gimnastico',
    capacities: ['velocidad'],
    primaryMuscleGroup: 'core',
    muscleGroups: ['core'],
    disciplines: ['funcional'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'jumping-jacks',
    name: 'Jumping Jacks',
    category: 'gimnastico',
    capacities: ['velocidad'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo'],
    disciplines: ['funcional'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'bear-crawl',
    name: 'Bear Crawl',
    category: 'gimnastico',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo'],
    disciplines: ['funcional'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'medicine-ball-slam',
    name: 'Medicine Ball Slam',
    category: 'gimnastico',
    capacities: ['potencia'],
    primaryMuscleGroup: 'core',
    muscleGroups: ['core', 'hombro'],
    disciplines: ['funcional'],
    equipment: 'balon_medicinal',
  },
  {
    catalogKey: 'box-step-up',
    name: 'Box Step-up',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'gluteo'],
    disciplines: ['funcional'],
    equipment: 'caja',
  },
  {
    catalogKey: 'kettlebell-goblet-squat',
    name: 'Kettlebell Goblet Squat',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'gluteo', 'core'],
    disciplines: ['funcional', 'hybrid'],
    equipment: 'kettlebell',
  },
  {
    catalogKey: 'lateral-band-walk',
    name: 'Lateral Band Walk',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'gluteo',
    muscleGroups: ['gluteo'],
    disciplines: ['funcional'],
    equipment: 'banda_elastica',
  },
  {
    catalogKey: 'jump-squat',
    name: 'Jump Squat',
    category: 'gimnastico',
    capacities: ['velocidad'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'gluteo'],
    disciplines: ['funcional'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'kettlebell-deadlift',
    name: 'Kettlebell Deadlift',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'isquiotibiales',
    muscleGroups: ['isquiotibiales', 'gluteo', 'espalda_baja'],
    disciplines: ['funcional', 'hybrid'],
    equipment: 'kettlebell',
  },
  {
    catalogKey: 'kettlebell-clean-and-press',
    name: 'Kettlebell Clean and Press',
    category: 'hipertrofia',
    capacities: ['potencia'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo', 'hombro', 'gluteo'],
    disciplines: ['funcional', 'hybrid'],
    equipment: 'kettlebell',
  },
  {
    catalogKey: 'turkish-get-up',
    name: 'Turkish Get-up',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo', 'hombro', 'core'],
    disciplines: ['funcional'],
    equipment: 'kettlebell',
  },
  {
    catalogKey: 'puente-gluteo',
    name: 'Puente de glúteo',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'gluteo',
    muscleGroups: ['gluteo', 'isquiotibiales'],
    disciplines: ['funcional', 'pilates'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'dead-bug',
    name: 'Dead Bug',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'core',
    muscleGroups: ['core'],
    disciplines: ['funcional', 'pilates'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'bird-dog',
    name: 'Bird Dog',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'core',
    muscleGroups: ['core', 'espalda_baja', 'gluteo'],
    disciplines: ['funcional', 'pilates'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'russian-twist',
    name: 'Russian Twist',
    category: 'gimnastico',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'core',
    muscleGroups: ['core'],
    disciplines: ['funcional'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'trx-squat',
    name: 'TRX Squat',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'gluteo', 'core'],
    disciplines: ['funcional'],
    equipment: 'trx',
  },
  // --- Running ---
  {
    catalogKey: 'carrera-100m',
    name: 'Carrera 100 m',
    category: 'running',
    capacities: ['velocidad'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps'],
    disciplines: ['running'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'carrera-400m',
    name: 'Carrera 400 m',
    category: 'running',
    capacities: ['velocidad'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps'],
    disciplines: ['running', 'crossfit', 'hybrid'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'carrera-1km',
    name: 'Carrera 1 km',
    category: 'running',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps'],
    disciplines: ['running', 'hybrid'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'carrera-5km',
    name: 'Carrera 5 km',
    category: 'running',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps'],
    disciplines: ['running', 'hybrid'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'carrera-10km',
    name: 'Carrera 10 km',
    category: 'running',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps'],
    disciplines: ['running'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'carrera-200m',
    name: 'Carrera 200 m',
    category: 'running',
    capacities: ['velocidad'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps'],
    disciplines: ['running'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'carrera-800m',
    name: 'Carrera 800 m',
    category: 'running',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps'],
    disciplines: ['running'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'carrera-1500m',
    name: 'Carrera 1500 m',
    category: 'running',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps'],
    disciplines: ['running'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'carrera-3km',
    name: 'Carrera 3 km',
    category: 'running',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps'],
    disciplines: ['running'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'carrera-21km',
    name: 'Carrera 21 km (media maratón)',
    category: 'running',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps'],
    disciplines: ['running'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'carrera-42km',
    name: 'Carrera 42 km (maratón)',
    category: 'running',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps'],
    disciplines: ['running'],
    equipment: 'sin_equipo',
  },
  // --- Hybrid ---
  {
    catalogKey: 'sandbag-over-shoulder',
    name: 'Sandbag Over Shoulder',
    category: 'hipertrofia',
    capacities: ['potencia'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo', 'espalda', 'gluteo'],
    disciplines: ['hybrid'],
    equipment: 'sandbag',
  },
  // --- Pilates ---
  {
    catalogKey: 'the-hundred',
    name: 'The Hundred',
    category: 'gimnastico',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'core',
    muscleGroups: ['core'],
    disciplines: ['pilates'],
    equipment: 'colchoneta',
  },
  {
    catalogKey: 'roll-up',
    name: 'Roll Up',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'core',
    muscleGroups: ['core'],
    disciplines: ['pilates'],
    equipment: 'colchoneta',
  },
  {
    catalogKey: 'single-leg-stretch',
    name: 'Single Leg Stretch',
    category: 'gimnastico',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'core',
    muscleGroups: ['core'],
    disciplines: ['pilates'],
    equipment: 'colchoneta',
  },
  {
    catalogKey: 'criss-cross',
    name: 'Criss Cross',
    category: 'gimnastico',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'core',
    muscleGroups: ['core'],
    disciplines: ['pilates'],
    equipment: 'colchoneta',
  },
  {
    catalogKey: 'teaser',
    name: 'Teaser',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'core',
    muscleGroups: ['core'],
    disciplines: ['pilates'],
    equipment: 'colchoneta',
  },
  {
    catalogKey: 'swan',
    name: 'Swan',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'espalda_baja',
    muscleGroups: ['espalda_baja', 'espalda'],
    disciplines: ['pilates'],
    equipment: 'colchoneta',
  },
  {
    catalogKey: 'side-leg-series',
    name: 'Side Leg Series',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'gluteo',
    muscleGroups: ['gluteo', 'core'],
    disciplines: ['pilates'],
    equipment: 'colchoneta',
  },
  {
    catalogKey: 'leg-circles',
    name: 'Leg Circles',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'core',
    muscleGroups: ['core', 'gluteo'],
    disciplines: ['pilates'],
    equipment: 'colchoneta',
  },
  {
    catalogKey: 'reformer-footwork',
    name: 'Reformer Footwork',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'gluteo', 'gemelo'],
    disciplines: ['pilates'],
    equipment: 'reformer',
  },
  {
    catalogKey: 'reformer-rowing',
    name: 'Reformer Rowing',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'espalda',
    muscleGroups: ['espalda', 'hombro', 'biceps'],
    disciplines: ['pilates'],
    equipment: 'reformer',
  },
  {
    catalogKey: 'aro-pilates-press-pecho',
    name: 'Aro Pilates Press de pecho',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'pectoral',
    muscleGroups: ['pectoral', 'hombro'],
    disciplines: ['pilates'],
    equipment: 'aro_pilates',
  },
  {
    catalogKey: 'pelota-pilates-curl-femoral',
    name: 'Pelota Pilates Curl femoral',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'isquiotibiales',
    muscleGroups: ['isquiotibiales', 'gluteo', 'core'],
    disciplines: ['pilates'],
    equipment: 'pelota_pilates',
  },
];
