import type { CatalogExerciseDefinition } from '@wasabi-cross/schemas';

/**
 * Definición de un ejercicio del catálogo pre-cargado. Además de nombre y categoría, lleva
 * lo que Estadísticas necesita para comparar por capacidad y grupo muscular, y lo que se
 * usa para buscar: disciplinas y equipo. El segmento no: sale del grupo primario.
 *
 * No lleva la medición: sale de la categoría (spec §5.1). Por eso la hipertrofia se mide en
 * repeticiones sin que nadie lo escriba acá.
 */
export type CatalogExercise = CatalogExerciseDefinition;

/**
 * Catálogo pre-cargado: los 62 ejercicios de spec §5.3 (ADR-0009). El usuario nuevo lo ve sin
 * tener que cargar nada.
 *
 * Cada entrada lleva una clave estable: el seed compara por ella, así que un ejercicio se
 * puede renombrar sin duplicarse. Un ejercicio que una disciplina mide distinto es otro
 * ejercicio: el Sled Push de funcional va en repeticiones y el de Hyrox, en metros.
 */
export const EXERCISE_CATALOG: readonly CatalogExercise[] = [
  // --- Gimnasio ---
  {
    catalogKey: 'back-squat',
    name: 'Sentadilla trasera',
    category: 'fuerza',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'gluteo', 'core'],
    disciplines: ['gimnasio'],
    equipment: 'barra',
  },
  {
    catalogKey: 'front-squat',
    name: 'Sentadilla frontal',
    category: 'fuerza',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'core', 'gluteo'],
    disciplines: ['gimnasio'],
    equipment: 'barra',
  },
  {
    catalogKey: 'peso-muerto-convencional',
    name: 'Peso muerto convencional',
    category: 'fuerza',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'isquiotibiales',
    muscleGroups: ['isquiotibiales', 'espalda_baja', 'gluteo', 'antebrazo'],
    disciplines: ['gimnasio'],
    equipment: 'barra',
  },
  {
    catalogKey: 'peso-muerto-rumano',
    name: 'Peso muerto rumano',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'isquiotibiales',
    muscleGroups: ['isquiotibiales', 'gluteo', 'espalda_baja'],
    disciplines: ['gimnasio'],
    equipment: 'barra',
  },
  {
    catalogKey: 'press-banca-plano',
    name: 'Press banca plano',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'pectoral',
    muscleGroups: ['pectoral', 'triceps', 'hombro'],
    disciplines: ['gimnasio'],
    equipment: 'barra',
  },
  {
    catalogKey: 'press-banca-inclinado',
    name: 'Press banca inclinado',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'pectoral',
    muscleGroups: ['pectoral', 'hombro', 'triceps'],
    disciplines: ['gimnasio'],
    equipment: 'barra',
  },
  {
    catalogKey: 'press-militar',
    name: 'Press militar',
    category: 'fuerza',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'hombro',
    muscleGroups: ['hombro', 'triceps', 'core'],
    disciplines: ['gimnasio'],
    equipment: 'barra',
  },
  {
    catalogKey: 'remo-con-barra',
    name: 'Remo con barra',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'espalda',
    muscleGroups: ['espalda', 'biceps'],
    disciplines: ['gimnasio'],
    equipment: 'barra',
  },
  {
    catalogKey: 'dominadas-lastradas',
    name: 'Dominadas lastradas',
    category: 'fuerza',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'espalda',
    muscleGroups: ['espalda', 'biceps'],
    disciplines: ['gimnasio'],
    equipment: 'barra_dominadas',
  },
  {
    catalogKey: 'curl-biceps-barra',
    name: 'Curl bíceps con barra',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'biceps',
    muscleGroups: ['biceps', 'antebrazo'],
    disciplines: ['gimnasio'],
    equipment: 'barra',
  },
  {
    catalogKey: 'curl-martillo',
    name: 'Curl martillo',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'antebrazo',
    muscleGroups: ['antebrazo'],
    disciplines: ['gimnasio'],
    equipment: 'mancuerna',
  },
  {
    catalogKey: 'extension-triceps-polea',
    name: 'Extensión tríceps en polea',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'triceps',
    muscleGroups: ['triceps'],
    disciplines: ['gimnasio'],
    equipment: 'polea',
  },
  {
    catalogKey: 'press-frances',
    name: 'Press francés',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'triceps',
    muscleGroups: ['triceps'],
    disciplines: ['gimnasio'],
    equipment: 'barra',
  },
  {
    catalogKey: 'prensa-piernas',
    name: 'Prensa de piernas',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps'],
    disciplines: ['gimnasio'],
    equipment: 'maquina',
  },
  {
    catalogKey: 'curl-femoral',
    name: 'Curl femoral',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'isquiotibiales',
    muscleGroups: ['isquiotibiales'],
    disciplines: ['gimnasio'],
    equipment: 'maquina',
  },
  {
    catalogKey: 'elevacion-gemelos',
    name: 'Elevación de gemelos',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'gemelo',
    muscleGroups: ['gemelo'],
    disciplines: ['gimnasio'],
    equipment: 'maquina',
  },
  {
    catalogKey: 'hip-thrust',
    name: 'Hip thrust',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'gluteo',
    muscleGroups: ['gluteo', 'isquiotibiales'],
    disciplines: ['gimnasio'],
    equipment: 'barra',
  },
  {
    catalogKey: 'elevaciones-laterales',
    name: 'Elevaciones laterales',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'hombro',
    muscleGroups: ['hombro'],
    disciplines: ['gimnasio'],
    equipment: 'mancuerna',
  },
  {
    catalogKey: 'crunch-abdominal',
    name: 'Crunch abdominal',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'core',
    muscleGroups: ['core'],
    disciplines: ['gimnasio'],
    equipment: 'sin_equipo',
  },
  // --- CrossFit ---
  {
    catalogKey: 'snatch',
    name: 'Snatch',
    category: 'fuerza',
    capacities: ['potencia'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo', 'hombro', 'espalda', 'cuadriceps'],
    disciplines: ['crossfit'],
    equipment: 'barra',
  },
  {
    catalogKey: 'clean-and-jerk',
    name: 'Clean and Jerk',
    category: 'fuerza',
    capacities: ['potencia'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo', 'hombro', 'cuadriceps', 'espalda'],
    disciplines: ['crossfit'],
    equipment: 'barra',
  },
  {
    catalogKey: 'push-press',
    name: 'Push Press',
    category: 'fuerza',
    capacities: ['potencia'],
    primaryMuscleGroup: 'hombro',
    muscleGroups: ['hombro', 'triceps', 'core'],
    disciplines: ['crossfit'],
    equipment: 'barra',
  },
  {
    catalogKey: 'overhead-squat',
    name: 'Overhead Squat',
    category: 'fuerza',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'hombro', 'core'],
    disciplines: ['crossfit'],
    equipment: 'barra',
  },
  {
    catalogKey: 'thruster',
    name: 'Thruster',
    category: 'hipertrofia',
    capacities: ['potencia'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo', 'hombro', 'gluteo'],
    disciplines: ['crossfit'],
    equipment: 'barra',
  },
  {
    catalogKey: 'wall-ball',
    name: 'Wall Ball',
    category: 'gimnastico',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo', 'cuadriceps', 'hombro'],
    disciplines: ['crossfit', 'hyrox'],
    equipment: 'balon_medicinal',
  },
  {
    catalogKey: 'kettlebell-swing',
    name: 'Kettlebell Swing',
    category: 'gimnastico',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'gluteo',
    muscleGroups: ['gluteo', 'core', 'isquiotibiales'],
    disciplines: ['crossfit'],
    equipment: 'kettlebell',
  },
  {
    catalogKey: 'pull-up',
    name: 'Pull-up',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'espalda',
    muscleGroups: ['espalda', 'biceps'],
    disciplines: ['crossfit'],
    equipment: 'barra_dominadas',
  },
  {
    catalogKey: 'toes-to-bar',
    name: 'Toes to Bar',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'core',
    muscleGroups: ['core', 'antebrazo'],
    disciplines: ['crossfit'],
    equipment: 'barra_dominadas',
  },
  {
    catalogKey: 'muscle-up',
    name: 'Muscle Up',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo', 'espalda', 'triceps'],
    disciplines: ['crossfit'],
    equipment: 'barra_dominadas_o_anillas',
  },
  {
    catalogKey: 'handstand-push-up',
    name: 'Handstand Push-up',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'hombro',
    muscleGroups: ['hombro', 'triceps'],
    disciplines: ['crossfit'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'box-jump',
    name: 'Box Jump',
    category: 'gimnastico',
    capacities: ['velocidad'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'gluteo'],
    disciplines: ['crossfit'],
    equipment: 'caja',
  },
  {
    catalogKey: 'burpee',
    name: 'Burpee',
    category: 'gimnastico',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo'],
    disciplines: ['crossfit'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'double-under',
    name: 'Double Under',
    category: 'gimnastico',
    capacities: ['velocidad'],
    primaryMuscleGroup: 'gemelo',
    muscleGroups: ['gemelo'],
    disciplines: ['crossfit'],
    equipment: 'cuerda_de_saltar',
  },
  {
    catalogKey: 'rope-climb',
    name: 'Rope Climb',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'espalda',
    muscleGroups: ['espalda', 'biceps', 'antebrazo'],
    disciplines: ['crossfit'],
    equipment: 'cuerda',
  },
  {
    catalogKey: 'remo-ergometro',
    name: 'Remo (ergómetro)',
    category: 'cardio',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo'],
    disciplines: ['crossfit', 'hyrox'],
    equipment: 'remoergometro',
  },
  {
    catalogKey: 'assault-bike',
    name: 'Assault Bike',
    category: 'cardio',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo'],
    disciplines: ['crossfit'],
    equipment: 'bicicleta_assault',
  },
  {
    catalogKey: 'ski-erg',
    name: 'SkiErg',
    category: 'cardio',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo'],
    disciplines: ['crossfit', 'hyrox'],
    equipment: 'skierg',
  },
  // --- Hyrox ---
  {
    catalogKey: 'sled-push-hyrox',
    name: 'Sled Push (Hyrox)',
    category: 'distancia_carga',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'gluteo', 'core'],
    disciplines: ['hyrox'],
    equipment: 'sled',
  },
  {
    catalogKey: 'sled-pull-hyrox',
    name: 'Sled Pull (Hyrox)',
    category: 'distancia_carga',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'espalda',
    muscleGroups: ['espalda', 'biceps'],
    disciplines: ['hyrox'],
    equipment: 'sled',
  },
  {
    catalogKey: 'farmers-carry-hyrox',
    name: 'Farmers Carry (Hyrox)',
    category: 'distancia_carga',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'antebrazo',
    muscleGroups: ['antebrazo', 'core', 'trapecio'],
    disciplines: ['hyrox'],
    equipment: 'mancuerna',
  },
  {
    catalogKey: 'sandbag-lunges',
    name: 'Sandbag Lunges',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'gluteo'],
    disciplines: ['hyrox'],
    equipment: 'sandbag',
  },
  {
    catalogKey: 'burpee-broad-jump',
    name: 'Burpee Broad Jump',
    category: 'gimnastico',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo'],
    disciplines: ['hyrox'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'carrera-1km-estacion',
    name: 'Carrera 1km (estación Hyrox)',
    category: 'running',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps'],
    disciplines: ['hyrox'],
    equipment: 'sin_equipo',
  },
  // --- Funcional ---
  {
    catalogKey: 'sled-push',
    name: 'Sled Push',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'gluteo', 'core'],
    disciplines: ['funcional'],
    equipment: 'sled',
  },
  {
    catalogKey: 'sled-pull',
    name: 'Sled Pull',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'espalda',
    muscleGroups: ['espalda', 'biceps'],
    disciplines: ['funcional'],
    equipment: 'sled',
  },
  {
    catalogKey: 'farmers-carry',
    name: 'Farmers Carry',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'antebrazo',
    muscleGroups: ['antebrazo', 'core', 'trapecio'],
    disciplines: ['funcional'],
    equipment: 'mancuerna',
  },
  {
    catalogKey: 'battle-ropes',
    name: 'Battle Ropes',
    category: 'gimnastico',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'hombro',
    muscleGroups: ['hombro', 'core'],
    disciplines: ['funcional'],
    equipment: 'cuerda_battle',
  },
  {
    catalogKey: 'trx-row',
    name: 'TRX Row',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'espalda',
    muscleGroups: ['espalda', 'biceps'],
    disciplines: ['funcional'],
    equipment: 'trx',
  },
  {
    catalogKey: 'trx-push-up',
    name: 'TRX Push-up',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'pectoral',
    muscleGroups: ['pectoral', 'triceps'],
    disciplines: ['funcional'],
    equipment: 'trx',
  },
  {
    catalogKey: 'mountain-climbers',
    name: 'Mountain Climbers',
    category: 'gimnastico',
    capacities: ['velocidad'],
    primaryMuscleGroup: 'core',
    muscleGroups: ['core'],
    disciplines: ['funcional'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'jumping-jacks',
    name: 'Jumping Jacks',
    category: 'gimnastico',
    capacities: ['velocidad'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo'],
    disciplines: ['funcional'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'bear-crawl',
    name: 'Bear Crawl',
    category: 'gimnastico',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo'],
    disciplines: ['funcional'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'medicine-ball-slam',
    name: 'Medicine Ball Slam',
    category: 'gimnastico',
    capacities: ['potencia'],
    primaryMuscleGroup: 'core',
    muscleGroups: ['core', 'hombro'],
    disciplines: ['funcional'],
    equipment: 'balon_medicinal',
  },
  {
    catalogKey: 'box-step-up',
    name: 'Box Step-up',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'gluteo'],
    disciplines: ['funcional'],
    equipment: 'caja',
  },
  {
    catalogKey: 'kettlebell-goblet-squat',
    name: 'Kettlebell Goblet Squat',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'gluteo', 'core'],
    disciplines: ['funcional'],
    equipment: 'kettlebell',
  },
  {
    catalogKey: 'lateral-band-walk',
    name: 'Lateral Band Walk',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'gluteo',
    muscleGroups: ['gluteo'],
    disciplines: ['funcional'],
    equipment: 'banda_elastica',
  },
  {
    catalogKey: 'jump-squat',
    name: 'Jump Squat',
    category: 'gimnastico',
    capacities: ['velocidad'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'gluteo'],
    disciplines: ['funcional'],
    equipment: 'sin_equipo',
  },
  // --- Running ---
  {
    catalogKey: 'carrera-100m',
    name: 'Carrera 100 m',
    category: 'running',
    capacities: ['velocidad'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps'],
    disciplines: ['running'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'carrera-400m',
    name: 'Carrera 400 m',
    category: 'running',
    capacities: ['velocidad'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps'],
    disciplines: ['running'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'carrera-1km',
    name: 'Carrera 1 km',
    category: 'running',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps'],
    disciplines: ['running'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'carrera-5km',
    name: 'Carrera 5 km',
    category: 'running',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps'],
    disciplines: ['running'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'carrera-10km',
    name: 'Carrera 10 km',
    category: 'running',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps'],
    disciplines: ['running'],
    equipment: 'sin_equipo',
  },
];
