import type { CatalogExerciseDefinition } from '@wasabi-cross/schemas';

/**
 * Definición de un ejercicio del catálogo pre-cargado. Además de nombre y categoría, lleva
 * lo que Estadísticas necesita para comparar por capacidad y grupo muscular, y lo que se
 * usa para buscar: disciplinas y equipo. El segmento no: sale del grupo primario.
 *
 * No lleva la medición: sale de la categoría (spec §5.1). Por eso la hipertrofia se mide en
 * repeticiones sin que nadie lo escriba acá.
 */
export type CatalogExercise = CatalogExerciseDefinition;

/**
 * Catálogo base (spec §5, F0-07). El usuario nuevo lo ve sin tener que cargar nada.
 *
 * Es el de la Fase 0, con la clave, el grupo primario (el primero de sus grupos), las
 * disciplinas y el equipo que pide el schema desde F5-01. Lo reemplazan los 62 de spec §5.3
 * en F5-05, que también pasa el seed a comparar por clave: hasta entonces compara por
 * nombre, así que renombrar un ejercicio acá crea uno nuevo en vez de actualizar el viejo.
 */
export const EXERCISE_CATALOG: readonly CatalogExercise[] = [
  // --- Fuerza: tren inferior ---
  {
    catalogKey: 'back-squat',
    name: 'Back squat',
    category: 'fuerza',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'gluteo', 'core'],
    disciplines: ['gimnasio', 'crossfit'],
    equipment: 'barra',
  },
  {
    catalogKey: 'front-squat',
    name: 'Front squat',
    category: 'fuerza',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'core'],
    disciplines: ['gimnasio', 'crossfit'],
    equipment: 'barra',
  },
  {
    catalogKey: 'overhead-squat',
    name: 'Overhead squat',
    category: 'fuerza',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'hombro', 'core'],
    disciplines: ['crossfit'],
    equipment: 'barra',
  },
  {
    catalogKey: 'peso-muerto',
    name: 'Peso muerto',
    category: 'fuerza',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'isquiotibiales',
    muscleGroups: ['isquiotibiales', 'gluteo', 'espalda'],
    disciplines: ['gimnasio', 'crossfit'],
    equipment: 'barra',
  },
  {
    catalogKey: 'peso-muerto-rumano',
    name: 'Peso muerto rumano',
    category: 'fuerza',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'isquiotibiales',
    muscleGroups: ['isquiotibiales', 'gluteo'],
    disciplines: ['gimnasio'],
    equipment: 'barra',
  },
  {
    catalogKey: 'hip-thruster',
    name: 'Hip thruster',
    category: 'fuerza',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'gluteo',
    muscleGroups: ['gluteo', 'isquiotibiales'],
    disciplines: ['gimnasio'],
    equipment: 'barra',
  },
  {
    catalogKey: 'estocada-con-mancuernas',
    name: 'Estocada con mancuernas',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'gluteo'],
    disciplines: ['gimnasio'],
    equipment: 'mancuerna',
  },
  {
    catalogKey: 'elevacion-de-gemelos',
    name: 'Elevación de gemelos',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'gemelo',
    muscleGroups: ['gemelo'],
    disciplines: ['gimnasio'],
    equipment: 'maquina',
  },

  // --- Fuerza: tren superior ---
  {
    catalogKey: 'press-de-banca',
    name: 'Press de banca',
    category: 'fuerza',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'pectoral',
    muscleGroups: ['pectoral', 'triceps', 'hombro'],
    disciplines: ['gimnasio'],
    equipment: 'barra',
  },
  {
    catalogKey: 'floor-press',
    name: 'Floor press',
    category: 'fuerza',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'pectoral',
    muscleGroups: ['pectoral', 'triceps'],
    disciplines: ['gimnasio'],
    equipment: 'barra',
  },
  {
    catalogKey: 'press-militar',
    name: 'Press militar',
    category: 'fuerza',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'hombro',
    muscleGroups: ['hombro', 'triceps', 'core'],
    disciplines: ['gimnasio'],
    equipment: 'barra',
  },
  {
    catalogKey: 'push-press',
    name: 'Push press',
    category: 'fuerza',
    capacities: ['fuerza', 'velocidad'],
    primaryMuscleGroup: 'hombro',
    muscleGroups: ['hombro', 'cuadriceps', 'triceps'],
    disciplines: ['crossfit'],
    equipment: 'barra',
  },
  {
    catalogKey: 'remo-con-barra',
    name: 'Remo con barra',
    category: 'fuerza',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'espalda',
    muscleGroups: ['espalda', 'biceps'],
    disciplines: ['gimnasio'],
    equipment: 'barra',
  },
  {
    catalogKey: 'butterfly',
    name: 'Butterfly',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'pectoral',
    muscleGroups: ['pectoral'],
    disciplines: ['gimnasio'],
    equipment: 'maquina',
  },
  {
    catalogKey: 'curl-de-biceps',
    name: 'Curl de biceps',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'biceps',
    muscleGroups: ['biceps', 'antebrazo'],
    disciplines: ['gimnasio'],
    equipment: 'barra',
  },
  {
    catalogKey: 'extension-de-triceps',
    name: 'Extensión de triceps',
    category: 'hipertrofia',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'triceps',
    muscleGroups: ['triceps'],
    disciplines: ['gimnasio'],
    equipment: 'polea',
  },

  // --- Halterofilia ---
  {
    catalogKey: 'snatch',
    name: 'Snatch',
    category: 'fuerza',
    capacities: ['fuerza', 'velocidad'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo'],
    disciplines: ['crossfit'],
    equipment: 'barra',
  },
  {
    catalogKey: 'clean-and-jerk',
    name: 'Clean and jerk',
    category: 'fuerza',
    capacities: ['fuerza', 'velocidad'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo'],
    disciplines: ['crossfit'],
    equipment: 'barra',
  },
  {
    catalogKey: 'power-clean',
    name: 'Power clean',
    category: 'fuerza',
    capacities: ['fuerza', 'velocidad'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo'],
    disciplines: ['crossfit'],
    equipment: 'barra',
  },
  {
    catalogKey: 'thruster',
    name: 'Thruster',
    category: 'fuerza',
    capacities: ['fuerza', 'resistencia'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'hombro'],
    disciplines: ['crossfit'],
    equipment: 'barra',
  },

  // --- Gimnástico: se miden en repeticiones ---
  {
    catalogKey: 'dominadas-estrictas',
    name: 'Dominadas estrictas',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'espalda',
    muscleGroups: ['espalda', 'biceps'],
    disciplines: ['gimnasio', 'crossfit'],
    equipment: 'barra_dominadas',
  },
  {
    catalogKey: 'pull-ups',
    name: 'Pull-ups',
    category: 'gimnastico',
    capacities: ['fuerza', 'resistencia'],
    primaryMuscleGroup: 'espalda',
    muscleGroups: ['espalda', 'biceps'],
    disciplines: ['crossfit'],
    equipment: 'barra_dominadas',
  },
  {
    catalogKey: 'fondos-en-paralelas',
    name: 'Fondos en paralelas',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'triceps',
    muscleGroups: ['triceps', 'pectoral'],
    disciplines: ['gimnasio'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'flexiones-de-brazos',
    name: 'Flexiones de brazos',
    category: 'gimnastico',
    capacities: ['fuerza', 'resistencia'],
    primaryMuscleGroup: 'pectoral',
    muscleGroups: ['pectoral', 'triceps'],
    disciplines: ['funcional'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'handstand-push-ups',
    name: 'Handstand push-ups',
    category: 'gimnastico',
    capacities: ['fuerza'],
    primaryMuscleGroup: 'hombro',
    muscleGroups: ['hombro', 'triceps'],
    disciplines: ['crossfit'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'toes-to-bar',
    name: 'Toes to bar',
    category: 'gimnastico',
    capacities: ['fuerza', 'resistencia'],
    primaryMuscleGroup: 'core',
    muscleGroups: ['core'],
    disciplines: ['crossfit'],
    equipment: 'barra_dominadas',
  },
  {
    catalogKey: 'burpees',
    name: 'Burpees',
    category: 'gimnastico',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuerpo_completo',
    muscleGroups: ['cuerpo_completo'],
    disciplines: ['crossfit'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'double-unders',
    name: 'Double unders',
    category: 'gimnastico',
    capacities: ['resistencia', 'velocidad'],
    primaryMuscleGroup: 'gemelo',
    muscleGroups: ['gemelo'],
    disciplines: ['crossfit'],
    equipment: 'cuerda_de_saltar',
  },

  // --- Running y remo: se miden en tiempo ---
  {
    catalogKey: 'sprint-100-m',
    name: 'Sprint 100 m',
    category: 'running',
    capacities: ['velocidad'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'isquiotibiales', 'gemelo'],
    disciplines: ['running'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'carrera-400-m',
    name: 'Carrera 400 m',
    category: 'running',
    capacities: ['velocidad', 'resistencia'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'isquiotibiales'],
    disciplines: ['running'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'carrera-1-km',
    name: 'Carrera 1 km',
    category: 'running',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'isquiotibiales', 'gemelo'],
    disciplines: ['running'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'carrera-5-km',
    name: 'Carrera 5 km',
    category: 'running',
    capacities: ['resistencia'],
    primaryMuscleGroup: 'cuadriceps',
    muscleGroups: ['cuadriceps', 'isquiotibiales', 'gemelo'],
    disciplines: ['running'],
    equipment: 'sin_equipo',
  },
  {
    catalogKey: 'row-500-m',
    name: 'Row 500 m',
    category: 'running',
    capacities: ['resistencia', 'velocidad'],
    primaryMuscleGroup: 'espalda',
    muscleGroups: ['espalda', 'cuadriceps'],
    disciplines: ['crossfit'],
    equipment: 'remoergometro',
  },
];
